print("Hello World!")
#print("Hello Again")
#print("I like typing this.")
#print("This isn't fun")
#print('Yay! Printing.')
#print("I'd much rather you 'not'.")
#print( 'I "said" do not touch  my bing bin bong:')
#print("print yet another line")
